# Generated by Django 5.0.6 on 2024-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/user-default-avatar.jpg', null=True, upload_to='media/avatars/'),
        ),
    ]
